name: Deployment On OCI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.OCI_DEPLOY_PATH }}
            git pull origin main
            npm install --production
            npm run build
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
